<center>
    <h1 style="color:blue">Data Science Stack - Numpy</h1>
</center>

<p>Numpy is used to <b>mathematic computation</b> with arrays/vectors and matrixes. It's not very recommended to be used in Data Analysis, however, understanding how Numpy works is the basic knowledge to get started in Data Analysis.</p>

<p>
    <b>OBS.:</b> you don't have to memoorize all of the methods and functions, you'll memorize them while you study and program. Don't be a fool!!
</p>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

<h2 style="color:blue">0 - Creating Vectors and Matrixes</h2>

<p>- Vectors/Arrays: is multi-dimmensional; to calculate the prooduct you must use <i>a @ b</i> OR <i>np.doot(a, b)</i></p>
<p>- Matrixes: can only be 2-D; to calculate the product you must use <i>a * b</i></p>

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = np.ones([3, 3])
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
c = np.zeros([3, 3])
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
e = np.diag([5, 5, 5])
e

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [8]:
# the second parameter determines at what column numpy will start inserting the diag values
f = np.diag([5, 5, 5], 1)
f

array([[0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5],
       [0, 0, 0, 0]])

In [9]:
# from first parameter to the second one assuming the third parameter as the step
# the second parameter is exclusive
g = np.arange(0, 10, 2.5)
g

array([0. , 2.5, 5. , 7.5])

In [10]:
# first parameter is the number of rows, whereas the second one is the number of columns
h = np.random.rand(5, 3)
h

array([[0.25229914, 0.19788177, 0.23611795],
       [0.99744144, 0.51318653, 0.06778941],
       [0.30018546, 0.37652789, 0.52045542],
       [0.87270911, 0.85687147, 0.5628813 ],
       [0.72257036, 0.33203013, 0.85474333]])

In [11]:
# creates an equal distributed array
# the first parameter is the start pooint, whereas the second one is the end point (both inclusive/non-exclusive)
# and the third parameter is the number of elements that I want within my array
i = np.linspace(1, 10, 5)
i

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

----

In [12]:
m = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

----

<h2 style="color:blue">1 - Properties and Functions</h2>

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# returns the number of dimensions
np.ndim(a)

2

In [15]:
# checks out the type of the object
type(a)

numpy.ndarray

In [16]:
# returns the number of rows and coolumns
a.shape

(3, 3)

In [17]:
# returns the amount of elements in the array
a.size

9

In [18]:
# returns the data type of the elements (must there is just one data type)
a.dtype

dtype('int32')

In [19]:
# mean, stardard variation, variance, summatory, cumulative summatory, product and cumulative product
results = {}

results['mean'] = np.mean(a)
results['stardard variation'] = np.std(a)
results['variance'] = np.var(a)
results['summatory'] = np.sum(a)
results['cumulative summatory'] = np.cumsum(a)
results['product'] = np.prod(a)
results['cumulative product'] = np.cumprod(a)

for key, value in results.items(): print(key, ': ', value)

mean :  5.0
stardard variation :  2.581988897471611
variance :  6.666666666666667
summatory :  45
cumulative summatory :  [ 1  3  6 10 15 21 28 36 45]
product :  362880
cumulative product :  [     1      2      6     24    120    720   5040  40320 362880]


In [20]:
# copies an array to another variable
# if you just assign on array to one variable, every modification you do in one variable
# will happen to the another one
a = np.array([1, 2, 3])
b = a

a[0] = 50
b[1] = 0

print('Without flatten method: ', a, b)

# to avoid this problem, we can use the flatten methood
a = np.array([1, 2, 3])
b = a.flatten()

a[0] = 50
b[1] = 0

print('With flatten method: ', a, b)

Without flatten method:  [50  0  3] [50  0  3]
With flatten method:  [50  2  3] [1 0 3]


In [21]:
# repeat >> repeats the element n times
# tile >> repeats the whole array n times
a = np.array([1, 2, 3])

print('Repeat Method: ', np.repeat(a, 2))
print('Tile Method: ', np.tile(a, 2))

Repeat Method:  [1 1 2 2 3 3]
Tile Method:  [1 2 3 1 2 3]


----

<center>
    <img src="thats all.jpg">
</center>